name: build
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['9.2.3', '9.4.5', '9.6.6', '9.8.4', '9.10.1']
        cabal: ['3.14.1.1']
        os: [ubuntu-latest, macOS-latest, windows-latest]
        exclude:
          - os: macOS-latest
            ghc: '9.2.3'
    name: "${{ matrix.os }} - ${{ matrix.ghc }}"
    steps:
      - uses: actions/checkout@v4
      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: cabal check
      - run: cabal update
      - run: cabal build
      - run: cabal test --test-show-details=direct --verbose
